deploy

diff --git a/.github/workflows/end_to_end_pipeline.yml b/.github/workflows/end_to_end_pipeline.yml
--- a/.github/workflows/end_to_end_pipeline.yml
+++ b/.github/workflows/end_to_end_pipeline.yml
@@ -9,122 +9,125 @@ on:
     branches: [ main ]
 
 jobs:
-  deploy_infrastructure:
-    runs-on: ubuntu-latest
-    outputs:
-      databricks_job_id: ${{ steps.tf_output.outputs.job_id }}
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+  # deploy_infrastructure:
+  #   runs-on: ubuntu-latest
+  #   outputs:
+  #     databricks_job_id: ${{ steps.tf_output.outputs.job_id }}
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
 
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v3
-        with:
-          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
+  #     - name: Setup Terraform
+  #       uses: hashicorp/setup-terraform@v3
+  #       with:
+  #         cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
 
-      - name: Terraform Init
-        env:
-          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
-          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
-        run: terraform init
-      - name: Terraform Apply
-        env:
-          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
-          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
-        run: terraform apply -auto-approve
+  #     - name: Terraform Init
+  #       env:
+  #         DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
+  #         DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
+  #       run: terraform init
+  #     - name: Terraform Apply
+  #       env:
+  #         DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
+  #         DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
+  #       run: terraform apply -auto-approve
 
-      - name: Capture Terraform Output
-        id: tf_output
-        run: echo "job_id=$(terraform output -raw databricks_job_id)" >> $GITHUB_OUTPUT
+  #     - name: Capture Terraform Output
+  #       id: tf_output
+  #       run: echo "job_id=$(terraform output -raw databricks_job_id)" >> $GITHUB_OUTPUT
 
 
-  run_pipeline_bronze:
-    runs-on: ubuntu-latest
-    needs: deploy_infrastructure
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+  # run_pipeline_bronze:
+  #   runs-on: ubuntu-latest
+  #   needs: deploy_infrastructure
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
       
-      - name: Setup Python
-        uses: actions/setup-python@v4
-        with:
-          python-version: '3.9'
-      - name: Install Databricks CLI
-        run: |
-          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
-      - name: Run Bronze Layer Job on Databricks
-        env:
-          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
-          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
-          JOB_ID_FROM_TF: ${{ needs.deploy_infrastructure.outputs.databricks_job_id }}
-        run: |
-          echo "Job ID received from Terraform: $JOB_ID_FROM_TF"
-          if [ -z "$JOB_ID_FROM_TF" ]; then
-            echo "Error: Job ID from Terraform is empty."
-            exit 1
-          fi
+  #     - name: Setup Python
+  #       uses: actions/setup-python@v4
+  #       with:
+  #         python-version: '3.9'
+  #     - name: Install Databricks CLI
+  #       run: |
+  #         curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
+  #     - name: Run Bronze Layer Job on Databricks
+  #       env:
+  #         DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
+  #         DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
+  #         JOB_ID_FROM_TF: ${{ needs.deploy_infrastructure.outputs.databricks_job_id }}
+  #       run: |
+  #         echo "Job ID received from Terraform: $JOB_ID_FROM_TF"
+  #         if [ -z "$JOB_ID_FROM_TF" ]; then
+  #           echo "Error: Job ID from Terraform is empty."
+  #           exit 1
+  #         fi
           
-          echo "Starting Databricks job run..."
-          RUN_ID=$(databricks jobs run-now $JOB_ID_FROM_TF | jq .run_id)
+  #         echo "Starting Databricks job run..."
+  #         RUN_ID=$(databricks jobs run-now $JOB_ID_FROM_TF | jq .run_id)
           
-          if [ -z "$RUN_ID" ]; then
-            echo "Failed to start job run."
-            exit 1
-          fi
-          echo "Job started with run_id: $RUN_ID"
+  #         if [ -z "$RUN_ID" ]; then
+  #           echo "Failed to start job run."
+  #           exit 1
+  #         fi
+  #         echo "Job started with run_id: $RUN_ID"
           
-          # --- CORREÇÃO FINAL AQUI ---
-          while true; do
-            # CORREÇÃO: Usar o RUN_ID como argumento posicional, sem a flag --run-id
-            STATUS_JSON=$(databricks jobs get-run $RUN_ID)
-            STATUS=$(echo $STATUS_JSON | jq -r .state.life_cycle_state)
-            echo "Current job status: $STATUS"
+  #         # --- CORREÇÃO FINAL AQUI ---
+  #         while true; do
+  #           # CORREÇÃO: Usar o RUN_ID como argumento posicional, sem a flag --run-id
+  #           STATUS_JSON=$(databricks jobs get-run $RUN_ID)
+  #           STATUS=$(echo $STATUS_JSON | jq -r .state.life_cycle_state)
+  #           echo "Current job status: $STATUS"
             
-            if [[ "$STATUS" == "TERMINATED" || "$STATUS" == "SKIPPED" ]]; then
-              RESULT_STATE=$(echo $STATUS_JSON | jq -r .state.result_state)
-              if [[ "$RESULT_STATE" == "SUCCESS" ]]; then
-                echo "Job completed successfully."
-                break
-              else
-                echo "Job failed with result state: $RESULT_STATE"
-                exit 1
-              fi
-            elif [[ "$STATUS" == "INTERNAL_ERROR" || "$STATUS" == "CANCELED" ]]; then
-              echo "Job failed with life cycle state: $STATUS"
-              exit 1
-            fi
-            sleep 30
-          done
+  #           if [[ "$STATUS" == "TERMINATED" || "$STATUS" == "SKIPPED" ]]; then
+  #             RESULT_STATE=$(echo $STATUS_JSON | jq -r .state.result_state)
+  #             if [[ "$RESULT_STATE" == "SUCCESS" ]]; then
+  #               echo "Job completed successfully."
+  #               break
+  #             else
+  #               echo "Job failed with result state: $RESULT_STATE"
+  #               exit 1
+  #             fi
+  #           elif [[ "$STATUS" == "INTERNAL_ERROR" || "$STATUS" == "CANCELED" ]]; then
+  #             echo "Job failed with life cycle state: $STATUS"
+  #             exit 1
+  #           fi
+  #           sleep 30
+  #         done
   
-  run_pipeline_dbt:
-    runs-on: ubuntu-latest
-    needs: run_pipeline_bronze
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-      - name: Setup Python
-        uses: actions/setup-python@v4
-        with:
-          python-version: '3.9'
-      - name: Install dbt packages
-        run: pip install dbt-core dbt-databricks
-      - name: Run dbt build (Silver and Gold Layers)
-        env:
-          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
-          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
-          DATABRICKS_HTTP_PATH: ${{ secrets.DATABRICKS_HTTP_PATH }}
-          DBT_CATALOG: "workspace"
-          DBT_SCHEMA: "case_ifood"
-        run: |
-          # Executa os comandos dbt especificando o diretório do projeto,
-          dbt deps --project-dir src/dbt_project
-          dbt build --project-dir src/dbt_project --profiles-dir src/dbt_project
+  # run_pipeline_dbt:
+  #   runs-on: ubuntu-latest
+  #   needs: run_pipeline_bronze
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
+  #     - name: Setup Python
+  #       uses: actions/setup-python@v4
+  #       with:
+  #         python-version: '3.9'
+  #     - name: Install dbt packages
+  #       run: pip install dbt-core dbt-databricks
+  #     - name: Run dbt build (Silver and Gold Layers)
+  #       env:
+  #         DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
+  #         DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
+  #         DATABRICKS_HTTP_PATH: ${{ secrets.DATABRICKS_HTTP_PATH }}
+  #         DBT_CATALOG: "workspace"
+  #         DBT_SCHEMA: "case_ifood"
+  #       run: |
+  #         # Executa os comandos dbt especificando o diretório do projeto,
+  #         dbt deps --project-dir src/dbt_project
+  #         dbt build --project-dir src/dbt_project --profiles-dir src/dbt_project
 
   deploy_dbt_docs:
     runs-on: ubuntu-latest
     needs: run_pipeline_dbt # Roda apenas após o sucesso do dbt build
     # Condição para rodar apenas em merges/pushes na branch 'main'
     if: github.ref == 'refs/heads/main'
+    
+    permissions:
+      contents: write
       
     steps:
       - name: Checkout code
